services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app_network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app_network
  
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:rw
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge